# Generated by Django 3.2.4 on 2021-08-24 16:50

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('readwrite', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_readwrite.post_set+', to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='MediaPostExternal',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='readwrite.post')),
                ('content', models.URLField()),
                ('origin', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('readwrite.post',),
        ),
        migrations.CreateModel(
            name='MediaPostInternal',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='readwrite.post')),
                ('content', models.FileField(upload_to='uploads/')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('readwrite.post',),
        ),
        migrations.CreateModel(
            name='TextPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='readwrite.post')),
                ('content', ckeditor.fields.RichTextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('readwrite.post',),
        ),
    ]
