# Generated by Django 3.2.4 on 2021-06-22 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readwrite', '0003_auto_20210622_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='author',
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter_position',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='readwrite.author'),
        ),
    ]
