# Generated by Django 3.2.4 on 2021-06-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readwrite', '0003_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(to='readwrite.Post'),
        ),
    ]
