# Generated by Django 3.2.4 on 2021-06-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readwrite', '0004_user_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='readwrite.Post'),
        ),
    ]
