# Generated by Django 3.2.4 on 2021-06-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readwrite', '0007_rename_user_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='darkmode',
            field=models.BooleanField(default=False),
        ),
    ]
