# Generated by Django 3.2.4 on 2021-06-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readwrite', '0008_user_darkmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='darkmode',
            field=models.CharField(choices=[('dark', 'Dark Mode'), ('light', 'Light Mode')], default='light', max_length=100),
        ),
    ]
