# Generated by Django 3.2.4 on 2021-06-27 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readwrite', '0009_alter_user_darkmode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='darkmode',
            new_name='color_mode',
        ),
    ]
